name = "hyperfiler-fresh-api"
main = "hyperfiler-backend/worker.js"
compatibility_date = "2024-07-01"

[env.production]
name = "hyperfiler-fresh-api"
main = "hyperfiler-backend/worker.js"
d1_databases = [
  { binding = "DB", database_name = "hyperfiler-prod", database_id = "47875cbd-ebb6-43d1-8109-6ccbc879c49e" }
]

# Admin authentication
[env.production.vars]
ADMIN_PASSWORD_HASH = "1e13e2850ba730320196de131b1d2f5602b1f3b432932cd2fce0f1401c559369:d42b1a58e0a9fc9eda2f476ad23ab1f85d2bd81a711015432de755f4fe3a8630"